### ISSUE TITLE
On an English site Relabel popup shows german translation

### ISSUE THREAD

**Issue by sergeifilippov** [Anubarak/craft-relabel#1]
On a English Craft 3 site, I get the following German translation in the popup ui.

![page - richmond mall 2018-10-08 10-45-09](https://user-images.githubusercontent.com/123676/46587337-958b7180-cae7-11e8-96ef-ed03fdd5e8bd.png)

**Comment by Anubarak** [comment]
Thanks for notifying me, this is fixed within [c85885f](https://github.com/Anubarak/craft-relabel/commit/c85885f2c5ea2be882a3eee8d2634a003b8e1bde#diff-3a0faa7837159025ecf11e626560dbe1R263)
