### ISSUE TITLE
Plugin doesn't seem to work in Craft 3.2.0

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [Anubarak/craft-relabel#10]
After updating Craft to 3.2.0 I get the folowing error when i try to edit certain entries (im guessing with fields that have been re labeled)
![Screenshot 2019-07-11 at 14 41 08](https://user-images.githubusercontent.com/50947605/61051701-f2ef7e80-a3e9-11e9-9a60-a21d9e3f9ded.png)

Thanks in advance

**Comment by Anubarak** [comment]
I had this too, can you confirm it's still an issue when you deactivate the plugin? Craft wasn't able to grab elements by ID for whatever reasons and I had to reinstall the migration.

I can include a check if the element is not null but Craft will throw an error instead.
