### ISSUE TITLE
Handle missing fields or layouts in a more graceful manner

### ISSUE THREAD

**Issue by andris-sevcenko** [Anubarak/craft-relabel#12]
There are scenarios where the plugin can leave the project config in a state that prevents importing into another site.

It seems that if, for example,  a matrix block type gets deleted, the corresponding labels in the project config do not get removed, even though the field layouts no longer exist.
This leaves the project config in a state, where if you apply it to a different environment, a DB error will be thrown because of non-nullable columns.

The easiest way to hotfix this is to check if [any of these calls return null](https://github.com/Anubarak/craft-relabel/blob/master/src/services/RelabelService.php#L711-L712), and, if so, skipping the (re)label.

**Comment by Anubarak** [comment]
Thanks for reporting that, I'll of course fix it but Relabel doesn't even work for fields in a matrix. I don't reference fields that are in the field layout of matrix block types so I'm a little bit confused why deleting them should be a thing.

What I mean is: there are no corresponding labels for a matrix block type.

**Comment by andris-sevcenko** [comment]
My bad, my then-context was just debugging a poject.yml file with a bunch of Matrix stuff. The same argument applies for a deleted entry-type, though where the field layout would get nuked. 

Also, I'm not very smart when writing things on GitHub, so I should have clarified that it would not be the most common stumbling block for Relabel.
