### ISSUE TITLE
Relabels no longer working in entries

### ISSUE THREAD

**Issue by brandondeweese** [Anubarak/craft-relabel#16]
Hi, When I relabel in the field layout designer, it works just fine. Once it's saved, the change doesn't take place in the entry fields, however, if I view in the field layout designer, the change seems to have saved correctly.

<img width="1078" alt="Screen Shot 2020-04-28 at 12 56 24 PM" src="https://user-images.githubusercontent.com/18017918/80531549-ad3b7c80-894f-11ea-9f51-063fc79aad7e.png">
<img width="1199" alt="Screen Shot 2020-04-28 at 12 56 03 PM" src="https://user-images.githubusercontent.com/18017918/80531617-c5ab9700-894f-11ea-9477-fc84b83714c3.png">

**Comment by Anubarak** [comment]
Are there any errors in the console? I cannot reproduce it unfortunately. It works quite well for me without any errors. Can you eventually provide more information?

**Comment by brandondeweese** [comment]
It says: Double-instantiating a menu button on an element." But that doesn't look like an error. Oddly enough, it works with only matrix fields. 

<img width="1278" alt="Screen Shot 2020-04-29 at 2 46 52 PM" src="https://user-images.githubusercontent.com/18017918/80650144-45a53000-8a28-11ea-9acf-7690bb13928f.png">

**Comment by Anubarak** [comment]
Could you eventually send me your db dump together with your composer.lock file to Anubarak1993@gmail.com?

I have really no clue what it is about. No matter what field combinations I test, it always works well

**Comment by frontedbe** [comment]
Can confirm this is occurring in several of my latest projects

**Comment by Anubarak** [comment]
@mdominguez Same question for you: are there any errors in your console and could you send me a DB dump? I am still not able to reproduce it

**Comment by Anubarak** [comment]
Thanks to @mdominguez  I was able to find the bug and created a new release with a fix.
Please let me know if there more issues

```
composer update anubarak/craft-relabel
```
should fix it.

**Comment by brandondeweese** [comment]
@Anubarak — Just updated to the latest Relabel (1.3.5.2) on my local machine and all relabels are no longer in CP. I have not updated on my live site, and relabels are working just fine. Seems like something broke with the update.
