### ISSUE TITLE
Relabels not showing after Relabel (1.3.5.2) update

### ISSUE THREAD

**Issue by brandondeweese** [Anubarak/craft-relabel#17]
Just updated to the latest Relabel (1.3.5.2) on my local machine and all relabels are no longer in CP. I have not updated on my live site, and relabels are working just fine. Seems like something broke with the update. Is anyone else seeing this?

**Comment by brandondeweese** [comment]
Just upgraded to Relabel 1.3.5.3 released on 6/22, and the problem still persists. No console errors.

**Comment by jorenvanhee** [comment]
1.3.5.4 fixes it for me.

**Comment by magnessjo** [comment]
I am still experiencing the issue using `1.3.5.4` within Neo `2.7.25` using craft `3.4.30`

**Comment by Anubarak** [comment]
Neo doesn't provide support for Relabel.

**Comment by magnessjo** [comment]
@Anubarak, thank you.  I didn't realize it wasn't supported.  I remember using it once upon a time but that could have been in Craft 2.
