### ISSUE TITLE
Doesn't work with Neo

### ISSUE THREAD

**Issue by christopherhealey** [Anubarak/craft-relabel#2]
As of right now it does not appear to work with NEO in Craft 3. All appears well except nothing is saved. You can click to save it however on refresh of the field, it is as if you never set any relabel.

**Comment by Anubarak** [comment]
The creator of Neo needs to include support for Relabel I provide the necessary events to create Relabeled field layouts but it requires too much effort and resources to figure out all Neo fields and set them properly.

As of now you won't be able to use Neo together with Relabel
