### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by its-me-mario** [Anubarak/craft-relabel#6]
After the plugin installs from the Plugin Store, I try to install from /Settings/Plugins/ and I get: "Could't install plugin". I don't see any errors in the logs.

I've tried multiple times with the same results and other plugins install with no issues.

**Comment by Anubarak** [comment]
What Version of Craft do you use?
I installed the latest version, installed the plugin and everything was fine. I'm sure there are errors in your logs if it's really a problem of the plugin, could you eventually search again?

**Comment by its-me-mario** [comment]
ah, I found the error in the logs:
`> create table {{%relabel}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_relabel' already exists...`

I manually removed the db table and it installed fine.

I was upgrading from Craft 2 (which had relabel installed before) and upgraded to Craft 3.1.9.1

**Comment by Anubarak** [comment]
Ahh I see. The previous plugin from Craft 2 was not mine and I didn't create a migration for it. That caused the issue.

Thanks for your investigation
