### ISSUE TITLE
Allow Markdown inside field instructions

### ISSUE THREAD

**Issue by rungta** [Anubarak/craft-relabel#7]
Craft allows Markdown inside the native field instructions. This comes handy when you want to italicise something, or provide a link. Relabel appears to support raw HTML but does not appear to process Markdown inside the descriptions. It would be great if you can add support for that. 

Cheers, and thank you for the plugin!

**Comment by Anubarak** [comment]
Thanks for that hint, I included the functionality to support Markdown, but only if there is no HTML between it. You can't use both  because this would break older projects of mine and I would need to relabel a few instructions manually.
I hope that's okay for you.

**Comment by rungta** [comment]
Works for me. Thanks!
